 
VALUES ('Prius','LE','','');
VALUES ('Prius','XLE','','');
VALUES ('Avalon','XLE','','');
VALUES ('Avalon','TRD','','');
VALUES ('Avalon','Limited','','');
VALUES ('Camry','LE','','');
VALUES ('Camry','XLE','','');
VALUES ('Camry','TRD','','');
VALUES ('Corolla','LE','','');
VALUES ('Corolla','XLE','','');
VALUES ('Supra','Base','','');
VALUES ('Supra','Premium','','');
VALUES ('RAV4','LE','','');
VALUES ('RAV4','XLE','','');
VALUES ('RAV4','Limited','','');
VALUES ('Highlander','LE','','','');
VALUES ('Highlander','XLE','','','');
VALUES ('Highlander','Limited','','');
VALUES ('Land Cruiser','Base','','');
VALUES ('Land Cruiser','Heritage','','');
VALUES ('Venza','LE','','');
VALUES ('Venza','XLE','','');
VALUES ('Venza','Limited','','');
VALUES ('Yaris','LE','','');
VALUES ('Yaris','XLE','','');
VALUES ('Sienna','LE','','');
VALUES ('Sienna','XLE','','');
VALUES ('Sienna','Limited','','');
VALUES ('CH-R','LE','','');
VALUES ('CH-R','XLE','','');
VALUES ('CH-R','Limited','','');
VALUES ('4Runner','Base','','');
VALUES ('4Runner','TRD','','');
VALUES ('86','Base','','');
VALUES ('86','TRD','','');
VALUES ('Tundra','SR','',''); 
VALUES ('Tacoma','SR','','');
VALUES ('Tacoma','Off-road','','');
 
VALUES ('IS','Base','','');
VALUES ('IS','Fsport','','');
VALUES ('ES','Base','','');
VALUES ('ES','Fsport','','');
VALUES ('LS','Base','','');
VALUES ('LS','Fsport','','');
VALUES ('GS','Base','','');
VALUES ('GS','Fsport','','');
VALUES ('LC','500h','','');
VALUES ('RC','Fsport','','');
VALUES ('GX','Base','','');
VALUES ('GX','Premium','','');
VALUES ('LX','Base','','');
VALUES ('LX','Premium','','');
VALUES ('LX','Fsport','','');
VALUES ('NX','Base','','');
VALUES ('NX','Fsport','','');
VALUES ('RX','Base','','');
VALUES ('RX','Fsport','','');
VALUES ('LFA','Base','','');
 
VALUES ('Accord','LX','','');
VALUES ('Accord','EX-L','','');
VALUES ('CR-V','LX','','');
VALUES ('CR-V','EX-L','','');
VALUES ('Civic','LX','','');
VALUES ('Civic','EX','','');
VALUES ('Clarity','Base','','');
VALUES ('Fit','LX','','');
VALUES ('Fit','EX-L','','');
VALUES ('HR-V','LX','','');
VALUES ('HR-V','EX_L','','');
VALUES ('Odyssey','LX','','');
VALUES ('Odyssey','EX-L','',''); 
VALUES ('Pilot','LX','','');
VALUES ('Pilot','EX-L','','');
VALUES ('Ridgeline','RTL','','');
 
VALUES ('ILX','Base','','');
VALUES ('ILX','Advance','','');
VALUES ('MDX','Base','','');
VALUES ('MDX','Advance','','');
VALUES ('NSX','Base','','');
VALUES ('NSX','Advance','','');
VALUES ('RDX','Base','','');
VALUES ('RDX','Advance','','');
VALUES ('RLX','Base','','');
VALUES ('RLX','Advance','','');
VALUES ('TLX','Base','','');
VALUES ('TLX','Advance','','');
 
VALUES ('Ascent','Base','','');
VALUES ('BRZ','Base','','');
VALUES ('Crosstrek','Base','','');
VALUES ('Forester','Base','','');
VALUES ('Impreza','Base','','');
VALUES ('Legacy','Base','','');
VALUES ('Outback','Base','','');
VALUES ('WRX','Base','','');
 
VALUES ('CX-3','Base','','');
VALUES ('CX-5','Base','','');
VALUES ('CX-9','Base','','');
VALUES ('MX-30','Base','','');
VALUES ('Miata','Base','','');
VALUES ('Mazda6','Base','','');
VALUES ('Mazda3','Base','','');
VALUES ('RX-8','Base','','');
VALUES ('RX-7','Base','','');
 
VALUES ('EV6','Base','','');
VALUES ('Forte','Base','','');
VALUES ('Forte5','Base','','');
VALUES ('K5','Base','','');
VALUES ('Niro','Base','','');
VALUES ('Optima','Base','','');
VALUES ('Rio','Base','','');
VALUES ('Seltos','Base','','');
VALUES ('Sorento','Base','','');
VALUES ('Soul','Base','','');
VALUES ('Stinger','Base','','');
VALUES ('Telluride','Base','','');
 
VALUES ('NEXO','Base','','');
VALUES ('Tucson','Base','','');
VALUES ('Veloster N','Base','','');
VALUES ('Senta','Base','','');
VALUES ('Accent','Base','','');
VALUES ('IONIQ','Base','','');
VALUES ('Venue','Base','','');
VALUES ('Sonata','Base','','');
VALUES ('Elantra','Base','','');
 
VALUES ('2 Series','Base','','');
VALUES ('3 Series','Base','','');
VALUES ('4 Series','Base','','');
VALUES ('5 Series','Base','','');
VALUES ('i3','Base','','');
VALUES ('i8','Base','','');
VALUES ('M3','Base','','');
VALUES ('M4','Base','','');
VALUES ('M5','Base','','');
VALUES ('M6','Base','','');
VALUES ('M8','Base','','');
VALUES ('X1','Base','','');
VALUES ('X3','Base','','');
VALUES ('X4','Base','','');
VALUES ('X5','Base','','');
VALUES ('X7','Base','','');
VALUES ('Z4','Base','','');
 
VALUES ('A-Class','Base','','');
VALUES ('B-Class','Base','','');
VALUES ('C-Class','Base','','');
VALUES ('E-Class','Base','','');
VALUES ('G-Class','Base','','');
VALUES ('R-Class','Base','','');
VALUES ('S-Class','Base','','');
VALUES ('Metris','Base','','');
 
VALUES ('A','Base','','');
VALUES ('Q','Base','','');
VALUES ('RS','Base','','');
VALUES ('S','Base','','');
VALUES ('TT','Base','','');
VALUES ('e-tron','Base','','');
VALUES ('R8','Base','','');
 
VALUES ('Boxster','Base','','');
VALUES ('Cayenne','Base','','');
VALUES ('Cayman','Base','','');
VALUES ('Macan','Base','','');
VALUES ('Panamera','Base','','');
VALUES ('911','Base','','');
 
VALUES ('Clubman','Base','','');
VALUES ('Countryman','Base','','');
VALUES ('Cooper','Base','','');
 
VALUES ('4C','Base','','');
VALUES ('Giulia','Base','','');
VALUES ('Stelvio','Base','','');
 
VALUES ('E-PACE','41800','','');
VALUES ('F-PACE','50900','','');
VALUES ('F-TYPE','69900','','');
VALUES ('XF','45300','','');
VALUES ('XJ','86500','','');
 
VALUES ('Bronco','30800','','');
VALUES ('E','43895','  ','');
VALUES ('Maverick','19995','','');
VALUES ('F150','30495','','');
VALUES ('Mustang','27205','','');
VALUES ('Expedition','69695','','');
VALUES ('Explorer','33745','','');
VALUES ('Edge','37145','','');
VALUES ('Ranger','25715','','');
VALUES ('Transit','26175','','');
VALUES ('GT','542676','','');
VALUES ('Escape','26760','','');
VALUES ('Focus','32705','','');
VALUES ('Fiesta','14260','','');
 
VALUES ('Avalanche','32400','','');
VALUES ('Bolt EV','31500','  ','');
VALUES ('Camaro','25000','','');
VALUES ('Captiva','21440','','');
VALUES ('Cobalt SS','21310','','');
VALUES ('Colorado','25435','','');
VALUES ('Corvette','60900','','');
VALUES ('Cruze','18870','','');
VALUES ('Equinox','25800','','');
VALUES ('Impala','27000','','');
VALUES ('Sonic','16295','','');
VALUES ('Spark EV','26000','','');
VALUES ('Suburban','53200','','');
VALUES ('Tahoe','50500','','');
VALUES ('TrailBlazer','21800','','');
VALUES ('Trax','21400','','');
 
VALUES ('Avenger','26000','','');
VALUES ('Caliber','12430','','');
VALUES ('Challenger','30075','','');
VALUES ('Charger','32500','','');
VALUES ('Dart','16100.','','');
VALUES ('Durango','36995','','');
VALUES ('Journey','29917','','');
VALUES ('Ram1500','35900','','');
 
VALUES ('C30','11300','','');
VALUES ('C70','22400','','');
VALUES ('V40','58750','','');
VALUES ('S60','39250','','');
VALUES ('S90','52850','','');
VALUES ('V60','46200','','');
VALUES ('V90','56200','','');
VALUES ('XC60','42650','','');
VALUES ('XC90','50900','','');
 
VALUES ('Cherokee','29995','','');
VALUES ('Compass','26390','','');
VALUES ('Gladiator','36085','','');
VALUES ('Renegade','24195','','');
VALUES ('Wrangler','29995','','');
VALUES ('Patriot','22000','','');
 
VALUES ('ATS','38995','','');
VALUES ('CT','37000','','');
VALUES ('DTS','48000','','');
VALUES ('ELR','75995','','');
VALUES ('Escalade','76295','','');
VALUES ('SRX','43995','','');
VALUES ('XT','35795','','');
 
VALUES ('Model S','99990','','');
VALUES ('Model 3','46990','','');
VALUES ('Model X','11990','','');
VALUES ('Model Y','62990','','');
VALUES ('Cybertruck','39900','','');